stages: [build]

variables:
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  IMAGE_LATEST: latest

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:latest
    entrypoint: [""]
  script:
    # login al registry interno con credenciales inyectadas por GitLab
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    # build + push (sha y latest)
    - /kaniko/executor
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/Dockerfile
        --destination $CI_REGISTRY_IMAGE:$IMAGE_TAG
        --destination $CI_REGISTRY_IMAGE:$IMAGE_LATEST
